name: Laravel CI - Colegio de Arquitectos

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, curl, libxml, zlib

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Check PHP Syntax
      # Esta versión es más simple y no falla con carpetas con espacios
      run: |
        php -l app/Http/Controllers/LoginController.php
        php -l routes/web.php
